/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as AskRouteImport } from './routes/ask'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuestionsIdRouteImport } from './routes/questions.$id'
import { Route as ModeratorQueueRouteImport } from './routes/moderator.queue'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as TagsTagRouteImport } from './routes/tags.$tag'
import { Route as AboutRouteImport } from './routes/about'
import { Route as HelpRouteImport } from './routes/help'
import { Route as TourRouteImport } from './routes/tour'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsIdRoute = QuestionsIdRouteImport.update({
  id: '/questions/$id',
  path: '/questions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeratorQueueRoute = ModeratorQueueRouteImport.update({
  id: '/moderator/queue',
  path: '/moderator/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsTagRoute = TagsTagRouteImport.update({
  id: '/tags/$tag',
  path: '/tags/$tag',
  getParentRoute: () => rootRouteImport,
} as any)

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const TourRoute = TourRouteImport.update({
  id: '/tour',
  path: '/tour',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ask': typeof AskRoute
  '/bookmarks': typeof BookmarksRoute
  '/login': typeof LoginRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/users': typeof AdminUsersRoute
  '/moderator/queue': typeof ModeratorQueueRoute
  '/questions/$id': typeof QuestionsIdRoute
  '/tags': typeof TagsRoute
  '/tags/$tag': typeof TagsTagRoute
  '/about': typeof AboutRoute
  '/help': typeof HelpRoute
  '/tour': typeof TourRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ask': typeof AskRoute
  '/bookmarks': typeof BookmarksRoute
  '/login': typeof LoginRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/users': typeof AdminUsersRoute
  '/moderator/queue': typeof ModeratorQueueRoute
  '/questions/$id': typeof QuestionsIdRoute
  '/tags': typeof TagsRoute
  '/tags/$tag': typeof TagsTagRoute
  '/about': typeof AboutRoute
  '/help': typeof HelpRoute
  '/tour': typeof TourRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ask': typeof AskRoute
  '/bookmarks': typeof BookmarksRoute
  '/login': typeof LoginRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/users': typeof AdminUsersRoute
  '/moderator/queue': typeof ModeratorQueueRoute
  '/questions/$id': typeof QuestionsIdRoute
  '/tags': typeof TagsRoute
  '/tags/$tag': typeof TagsTagRoute
  '/about': typeof AboutRoute
  '/help': typeof HelpRoute
  '/tour': typeof TourRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ask'
    | '/bookmarks'
    | '/login'
    | '/forgot-password'
    | '/profile'
    | '/register'
    | '/verify-email'
    | '/admin/users'
    | '/moderator/queue'
    | '/questions/$id'
    | '/tags'
    | '/tags/$tag'
    | '/about'
    | '/help'
    | '/tour'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ask'
    | '/bookmarks'
    | '/login'
    | '/forgot-password'
    | '/profile'
    | '/register'
    | '/verify-email'
    | '/admin/users'
    | '/moderator/queue'
    | '/questions/$id'
    | '/tags'
    | '/tags/$tag'
      | '/about'
      | '/help'
      | '/tour'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ask'
    | '/bookmarks'
    | '/login'
    | '/profile'
    | '/register'
    | '/admin/users'
    | '/moderator/queue'
    | '/questions/$id'
    | '/tags'
    | '/tags/$tag'
      | '/about'
      | '/help'
      | '/tour'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AskRoute: typeof AskRoute
  BookmarksRoute: typeof BookmarksRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ModeratorQueueRoute: typeof ModeratorQueueRoute
  QuestionsIdRoute: typeof QuestionsIdRoute
  TagsRoute: typeof TagsRoute
  TagsTagRoute: typeof TagsTagRoute
  AboutRoute: typeof AboutRoute
  HelpRoute: typeof HelpRoute
  TourRoute: typeof TourRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
      '/forgot-password': {
        id: '/forgot-password'
        path: '/forgot-password'
        fullPath: '/forgot-password'
        preLoaderRoute: typeof ForgotPasswordRouteImport
        parentRoute: typeof rootRouteImport
      }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
      '/verify-email': {
        id: '/verify-email'
        path: '/verify-email'
        fullPath: '/verify-email'
        preLoaderRoute: typeof VerifyEmailRouteImport
        parentRoute: typeof rootRouteImport
      }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/$id': {
      id: '/questions/$id'
      path: '/questions/$id'
      fullPath: '/questions/$id'
      preLoaderRoute: typeof QuestionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderator/queue': {
      id: '/moderator/queue'
      path: '/moderator/queue'
      fullPath: '/moderator/queue'
      preLoaderRoute: typeof ModeratorQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$tag': {
      id: '/tags/$tag'
      path: '/tags/$tag'
      fullPath: '/tags/$tag'
      preLoaderRoute: typeof TagsTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour': {
      id: '/tour'
      path: '/tour'
      fullPath: '/tour'
      preLoaderRoute: typeof TourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AskRoute: AskRoute,
  BookmarksRoute: BookmarksRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ModeratorQueueRoute: ModeratorQueueRoute,
  QuestionsIdRoute: QuestionsIdRoute,
  TagsRoute: TagsRoute,
  TagsTagRoute: TagsTagRoute,
  AboutRoute: AboutRoute,
  HelpRoute: HelpRoute,
  TourRoute: TourRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
