spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://db:5432/${DB_NAME}?currentSchema=techforum
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    create-schemas: true
    schemas: techforum
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_batch_fetch_size: 50
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 25
          time_zone: UTC

  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1

  ai:
    google:
      genai:
        api-key: ${LLM_API_KEY}
        chat:
          model: gemini-2.0-flash

server:
  servlet:
    context-path: /api

application:
  security:
    jwt:
      secret-key: f62ee1d6eaa7d0fc352f6ac8b6cb8523d7967120a7b73bd16ea67ce2ced683ecf2b83ad079ad64b818b117299e45b481732557238040888a40de0008bb473b22
      expiration-time: 86400000