name: PR CI - Spring Boot Build

on:
  pull_request:
    branches: [ "main" ]
    paths: ["backend/**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build and Test with Maven
        run: mvn -B clean package
        working-directory: ./backend

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: backend/target/surefire-reports/

      - name: Verify Dockerfile
        run: docker build -t techforum-backend-test ./backend